language: elixir
elixir:
- 1.4.2
script:
- mix test --no-start
env:
  global:
    secure: 0AWmlexkAt0bSYMcR6F/rNN5Q/qUKkuEuv/UIEMLmgdz3YQO13tC8t6gg5ZWJuNvCdMSljCGcuy3weRFbskA5LpB6FXdcoV/71Yi87I7ou4Uprm/7qsMkp65Q6mk0hoQzxI3yLWu+BL1ULGNB3tu7MGv3QTqbbYc5peYxKviM+Ri4WrNPDvkii3qkyPqt+tXonUr8e5b0ibYgxPbbMhfqWH7EQSo8jvm01yP737ruHCytvs6mnzFXN19VbZkn/WO/DEb/on3iRG+n7IAYUlYpwT8xg8b25ePOrhJHRRDVE7cse4FMVVuWXDTbK5tddZbHYshvnQ83eShaYsl2W5eZVgko6xKPDoLDr8k9aTUqXKylHhSmns+ahp/uA9ktwM7mmIUuGo78pxvAAgmUhG0viMdZBuDnJYz9YbHuH9sMR6MNsgPRtL7TIdls0QoRBwkl17TJEGg8UKpU+OD3gniZkp4F/zgFwssc/b2fYYsi0hBwQROjlGmz+WTdhqm2zSp0nNn4VwVHC6Eqhq7clRImMzVCjZSKgM0DCON39fc9lcyb0VUNB0USl/QfIlXsx1dZuceO2dcGdtg5v/KfQqauKDhP0ekiSLQWzHX0GIGt2/upD6AN/NoWNyxlORvEp7MWco+qrqIxHl9i5rNDdKP5EL6iNP+2uQvZExpS7cgOfE=
